load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

cc_test(
    name = "cpplib_test",
    srcs = ["cpplib_test.cc"],
    deps = [
        "//src/lib:CPPLib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "sort_test",
    srcs = ["sort_test.cc"],
    deps = [
        "//src/lib/sort:SortLib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "search_test",
    srcs = ["search_test.cc"],
    deps = [
        "//src/lib/search:SearchLib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_fixture",
    srcs = ["test_fixture.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gmock",
    srcs = ["gmock.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gmock2",
    srcs = ["gmock2.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "findmax_test",
    srcs = ["findmax_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "hello_world_test",
    srcs = ["hello_world_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "hello_world_test_main",
    srcs = ["hello_world_test_main.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "fib_test",
    srcs = ["fib_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "sort_test_function",
    srcs = ["sort_test_function.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_fixture_shared_resources",
    srcs = ["test_fixture_shared_resources.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "sort_test_function_test_param",
    srcs = ["sort_test_function_test_param.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "sort_test_function_share_test_logic",
    srcs = ["sort_test_function_share_test_logic.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
