load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "matchers_intro",
    size = "small",
    srcs = ["matchers_intro.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "matcher_examples",
    srcs = ["matcher_examples.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "strings",
    srcs = ["strings.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "composite",
    srcs = ["composite.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "container",
    srcs = ["container.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "member",
    srcs = ["member.cc"],
    copts = ["--std=c++17"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "floating_point",
    srcs = ["floating_point.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "predicates",
    srcs = ["predicates.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "pointer",
    srcs = ["pointer.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "describe",
    srcs = ["describe.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "comparison",
    srcs = ["comparison.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "optional",
    srcs = ["optional.cc"],
    copts = ["--std=c++17"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "custom_matchers",
    srcs = ["custom_matchers.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
