load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "matchers_intro",
    srcs = ["matchers_intro.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "matcher_examples",
    srcs = ["matcher_examples.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
