load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "private_ptr",
    srcs = ["private_ptr.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "exception_mock",
    srcs = ["exception_mock.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "exception",
    srcs = ["exception.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "return_and_assign",
    srcs = ["return_and_assign.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "use_the_arg_in_return_value",
    srcs = ["use_the_arg_in_return_value.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "bit_manipulation",
    srcs = ["bit_manipulation.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
