load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "events_publisher",
    hdrs = ["events_publisher.h"],
    deps = [
        "//src/feed_event:feed_event",
    ],
)